### ISSUE TITLE
Render pages based on A/B samples

### ISSUE THREAD

**Issue by johngian** [mozilla/sumo-experiments#11]
Integrate A/B testing samples with how kitsune renders web pages for the specific articles.

**Comment by akatsoulas** [comment]
We need to clarify if a user who gets the new page of one article should also get the new page for the second article (if visited) or this decision will be a 50/50 chance. cc @madasan

**Comment by madasan** [comment]
Decision: 50/50 chance

**Comment by akatsoulas** [comment]
The experiments are setup for a 50/50 distribution.
