### ISSUE TITLE
Add links for Terms and Sitemap.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-experiments#25]

**Comment by akatsoulas** [comment]
cc @madasan to get the actual links for these entries.

**Comment by madasan** [comment]
@jonisavage can you provide these?

**Comment by jonichan** [comment]
Here are the links: 

First sentence: “Cookies”: https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer 

Step #3:  “Disable third party cookies in Firefox to stop some types of tracking by advertisers.” : https://support.mozilla.org/en-US/kb/disable-third-party-cookies 

Last paragraph: “Websites say cookies are blocked — unblock them”: https://support.mozilla.org/en-US/kb/websites-say-cookies-are-blocked-unblock-them

**Comment by akatsoulas** [comment]
@jonisavage thanks for the input. Are there any links for the `Sitemap` and the `Terms` located at the footer of the page? I couldn't find such links in SuMo.

https://ramotion.github.io/sumo-experiments/index.html#

**Comment by jonichan** [comment]
Let's remove the Site Map and Terms links from the footer as the footer should be consistent with Mozilla's other sites.

**Comment by akatsoulas** [comment]
This is now fixed.
