### ISSUE TITLE
Ramotion/sumo-experiments is out of sync with upstream

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-experiments#31]
We just realized that the master branch of https://github.com/Ramotion/sumo-experiments/ contains changes that are not pushed in this repository. This has as a result that functionality that was added after the first PR with the initial commits in not present in the current repository

**Comment by akatsoulas** [comment]
@Juriv can we open a PR with everything that is missing here?

**Comment by Juriv** [comment]
@akatsoulas https://github.com/mozilla/sumo-experiments/pull/32 
please check and let me know if you need any help

**Comment by Juriv** [comment]
@akatsoulas could you please deploy your version to gh-pages or somewhere else so we could give designers/qa links to compare your version and ours

**Comment by akatsoulas** [comment]
@Juriv I am in the process of integrating the code from your PR in the templates that are used in the Mozilla Support site. I will open an issue and assign it to you when it's deployed in the staging server (https://support.allizom.org/)

**Comment by akatsoulas** [comment]
@Juriv the experiments are in the staging server. @rleitan @viorelaioia did some QA on the page and filed a few issues in this repository. The experiment urls are:
https://support.allizom.org/en-US/kb/exp/enable-and-disable-cookies-website-preferences
https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox
