### ISSUE TITLE
The nav menu is scrolled down with the page and overlaps the page content

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-experiments#36]
[Environment]:
iOS, Windows 10, Mac OS 10.14 - Firefox, Chrome, Safari

[Steps to reproduce]:
1. Open https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox
2. Scroll the page down

[Expected result]:
The nav menu should not be scrolled down

[Actual result]:
The nav menu is scrolled down with the page and overlaps the page content
https://vimeo.com/317943871 

[Note]:
On prod is displayed the header when the page is scrolled down

**Comment by akatsoulas** [comment]
@Juriv thoughts?

**Comment by akatsoulas** [comment]
This is fixed here:
https://github.com/mozilla/kitsune/pull/3466

**Comment by rleitan** [comment]
I confirm it's fixed.
