### ISSUE TITLE
[Windows]: A scrollbar is displayed for all options displayed in the nav menu 

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-experiments#37]
[Environment]:
Windows 10 - Firefox, Chrome, Edge

[STR]:
1.Open https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox
2.Go the nav menu options (e.g. Cookies and cache)
3.Click the down arrow to open the menu

[Expected result]:
The menu should be opened. No scrollbar should be displayed

[Actual result]:
The menu is opened. A scrollbar is displayed in the right side for all options displayed in the nav menu 
![2019-02-18_11h28_12](https://user-images.githubusercontent.com/41474886/52951204-d6df3800-3389-11e9-9624-1a1ad79b4653.png)

[Note]:
On Chrome and Edge, when the menu is opened the browser's scrollbar is not displayed anymore. The scrollbar reappears when the menu is closed
Not reproducible on Mac, Ubuntu or iOS

**Comment by akatsoulas** [comment]
@Juriv thoughts?

**Comment by rleitan** [comment]
I still reproduce the issue described in Note
"when the menu is opened the browser's scrollbar is not displayed anymore. The scrollbar reappears when the menu is closed"
 
@Juriv

**Comment by Juriv** [comment]
@rleitan i'll check

**Comment by vladsov** [comment]
@rleitan there are two correct solutions:
allow to scroll the page when the menu is opened
or leave as it is
