### ISSUE TITLE
"Sign in" button displayed on experiments page instead of my account after a successful login

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-experiments#38]
[Environment]:
All platforms- all browsers

[STR]:
1.Open https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox
2.Go to header and click "Sign in" 
3.Enter valid credentials

[Expected result]:
The page should be redirected to the article from where I clicked Sign in"

[Actual result]:
The page is redirected to https://support.allizom.org/en-US/. Login is successful, but when I navigate to experiment page I'm not logged in

**Comment by akatsoulas** [comment]
The header changes significantly when users are logging in and it's not only the `Sign In` button. Because of that we will enable the experiments only for non-logged in users.
