### ISSUE TITLE
Video plays from the beginning when clicking each picture

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/sumo-experiments#39]
**Env:**
All platforms and browsers.

**STR:** 
1. Navigate to https://support.allizom.org/en-US/kb/insecure-password-warning-firefox
2. Click the "Play" button in the video => Video starts playing from the beginning
3. Pause the video
4. Click the next picture above the video
5. Click the "Play" button again

**Expected:**
Video starts playing from a certain time different than the beginning. Pictures are different.

**Actual:**
Video starts playing from the beginning, pictures are the same. See [https://vimeo.com/317972332](https://vimeo.com/317972332)

**Comment by akatsoulas** [comment]
@madasan @Juriv is this the intended behavior?

**Comment by madasan** [comment]
@jonisavage can you help on this one?

**Comment by akatsoulas** [comment]
This is merged - pending deployment to stage

**Comment by viorelaioia-zz** [comment]
This issue is fixed.
