### ISSUE TITLE
Extra like / dislike buttons available for the video

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/sumo-experiments#40]
Like and dislike buttons are displayed 2 times on the page (bottom of the video, bottom of the article) and they have same functionality: to get feedback for the article. The buttons should be removed from the video, as they are rating the article, not the video.

![like-dislike](https://user-images.githubusercontent.com/5293100/52953830-41e03d00-3391-11e9-8272-3bb50b05d597.png)

**Comment by akatsoulas** [comment]
Actually for this experiment, extra feedback is needed for the video. I believe we can close this issue. cc @madasan thoughts?

**Comment by madasan** [comment]
That's correct, we need the extra feedback for the video. Feel free to close this issue.

**Comment by viorelaioia-zz** [comment]
Closing the issue, as per comments above.

**Comment by rleitan** [comment]
@madasan, on https://support.allizom.org/en-US/kb/exp/enable-and-disable-cookies-website-preferences like and dislike buttons are not available for video. is this expected?
