### ISSUE TITLE
[IE] The experiment page is displayed if I paste the exp link in the address bar

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-experiments#42]
[Environment]:
Windows 10 - Internet Explorer ver.11.590.17134.0

[STR]:
1. Go to https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox page

[Expected result]:
The page should be redirected to https://support.allizom.org/en-US/kb/insecure-password-warning-firefox  ( the old UI)

[Actual result]:
The experiment page is displayed

[Note]:
The issue is reproducible for both experiments
If I go to support.allizom.org and search for the article, it takes me to the old UI, as expected

**Comment by akatsoulas** [comment]
This is fixed in stage

**Comment by rleitan** [comment]
The issue is verified as fixed!
