### ISSUE TITLE
Video preview is not visible until clicking on play button

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-experiments#44]
[Environment]:
iOS - Firefox, Safari,
Android - Firefox

[STR]:
1.Open https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox

[Expected result]:
Video preview should be displayed on the page

[Actual result]:
The video preview is not visible, only the play button is visible
![img_0038](https://user-images.githubusercontent.com/41474886/53011917-369d1800-344a-11e9-82cc-76b8908c9709.PNG)

**Comment by akatsoulas** [comment]
@Juriv is there an update on this? cc @madasan

**Comment by vladsov** [comment]
Each video tag must have a `poster` attribute
```html
<video controls poster="video/enable-and-disable-cookies.png"></video>
```

**Comment by rleitan** [comment]
I confirm it's fixed now!
