### ISSUE TITLE
Text placeholder is not visible for the video feedback form

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-experiments#50]
[Environment]:
All platforms- all browsers

[STR]:
1.Open https://support.allizom.org/en-US/kb/exp/insecure-password-warning-firefox
2.Cick the "thumb down" button located under the video
3.Click the text box

[Expected result]:
"How can we make it better" text should be displayed as placeholder
The type caret should be displayed in the upper left corner

[Actual result]:
Text placeholder is not visible
The caret is displayed in the centre of the text box
workaround: pressing backspace/delete and moving the caret to the upper left corner will display the "How can we make it better" text

[Note]:
The issue is not reproducible for the other feedback section

**Comment by akatsoulas** [comment]
nice catch! PR opened here
https://github.com/mozilla/kitsune/pull/3471

**Comment by akatsoulas** [comment]
This is fixed in stage.

**Comment by rleitan** [comment]
I confirm it's fixed!
